feat: bond creation
ixofoundation/ixo-webclient pull request #1358
Opened 2023-08-29 12:21 UTC by gsSuper

## Scope

## Work Done

## Steps to Test

## Screenshots

2023-10-09 08:26 UTC, alwyn-ixo requested changes
@gsSuper Update the Swimm documentation, please.

2023-10-12 06:53 UTC, Zach-ixo approved these changes, later dismissed

2023-10-16 10:05 UTC, Zach-ixo submitted a review, later dismissed

2023-10-16 10:07 UTC, Zach-ixo commented
@gsSuper PR needs conflict resolution

2023-10-16 12:10 UTC, gsSuper commented
> @gsSuper PR needs conflict resolution

@Zach-ixo Conflict's resolved 👍

2023-10-16 12:44 UTC, alwyn-ixo approved these changes

2023-10-16 13:48 UTC, merged