fix: add delay between dao state fetching
ixofoundation/ixo-webclient pull request #1396
Opened 2023-10-05 15:41 UTC by gsSuper

## Scope

## Work Done

## Steps to Test

## Screenshots

2023-10-06 05:34 UTC, Zach-ixo commented on src/components/App/App.tsx
> +          await sleep(3 * 1000)
@gsSuper does this sleep have any effect on the RPC calls and their RPS. I noticed you changed the interval in sleepByLimiter to 3 request per interval, I think that should do it.

2023-10-06 05:37 UTC, Zach-ixo commented on src/utils/dao.ts
@gsSuper something we can consider in future is to add exponential back-offs in case where some calls fails. We can do that through error handling, and retry those calls that fails with status 429

2023-10-06 05:38 UTC, Zach-ixo approved these changes

2023-10-09 08:23 UTC, alwyn-ixo requested changes

2023-10-09 08:23 UTC, alwyn-ixo commented on src/components/App/App.tsx
> +          await sleep(3 * 1000)
@gsSuper The 3 second sleep does not make sense to me.
Can you explain the details?

2023-10-09 08:25 UTC, alwyn-ixo commented on src/components/App/App.tsx
> +          await sleep(3 * 1000)
@gsSuper Update Swimm docs with your explanation, please.

2023-10-13 13:29 UTC, Zach-ixo submitted a review, later dismissed

2023-10-13 13:55 UTC, Zach-ixo approved these changes

2023-10-13 13:58 UTC, alwyn-ixo approved these changes

2023-10-13 13:58 UTC, merged