Khanh funding page
ixofoundation/ixo-webclient pull request #267
Opened 2020-08-04 14:25 UTC by self-coding-crab

## Scope

## Work Done
enhance funding page
- add apex charts
- add react spring
- create a transaction table
- modify the header style
- add a mobile responsive table
- refactor routing module
- create mobile responsive funding page ( sidebar, header )
- refactor module includes part
## Steps to Test

## Screenshots

2020-08-05 08:25 UTC, erezgreenberg requested changes
Hey Khanh

Looks good overall - just a few things.

1) Can you use node version 9.6.1 - we use a .node-version file to make sure it switches to correct version

2) The header on the individual project/cell page looks a bit squashed

![image](https://user-images.githubusercontent.com/20910282/89389652-f7c65500-d705-11ea-8112-dbb3379724ad.png)


3) The bond buy / sell text is very light. Or will this be a different task?

![image](https://user-images.githubusercontent.com/20910282/89389686-03198080-d706-11ea-9c44-8cd13d11047f.png)

2020-08-05 17:16 UTC, self-coding-crab commented
I checked it on node v9.6 and works well.
Regarding feedback 2, it will be fixed in the next version.
For feedback 3, yes, it's a kinda different task.

2020-08-07 12:14 UTC, erezgreenberg approved these changes

2020-08-07 12:14 UTC, erezgreenberg approved these changes

2020-08-07 12:14 UTC, merged