Fix:[IXO-914] change default filter for project explorer
ixofoundation/ixo-webclient pull request #921
Opened 2022-06-03 17:49 UTC by vaibhavphutane

## Screenshots
![image](https://user-images.githubusercontent.com/14000470/171918865-fe659681-2a6d-40cb-b7ad-09fe58b608c3.png)

2022-06-05 15:42 UTC, elite0226 requested changes

2022-06-05 15:42 UTC, elite0226 commented on configs/testzone/config.json
> +        "selectedTags": [],
Should not be changed.
I think we should have `Global` selected as default.

2022-06-05 15:42 UTC, elite0226 commented on configs/testzone/config.json
> +          "selectedTags": [],
LGTM!

2022-06-08 19:43 UTC, demondayza commented
There are pending requested changes from @elite0226 , please implement @vaibhavphutane

2022-06-08 19:55 UTC, elite0226 approved these changes

2022-06-09 08:10 UTC, merged